/**
 * Care-team inbox (messaging on top of the mocked clinician-in-the-loop queue).
 * Each thread hangs off a review_flag. The "reviewer" side is ALWAYS simulated
 * and clearly labeled — nothing here implies a real human read or replied.
 * Every function is ownership-scoped by userId; mutations verify ownership.
 */
import { and, asc, desc, eq } from "drizzle-orm";
import { db } from "../db/client";
import { threadMessages, reviewFlags, type ThreadMessage, type ReviewFlag } from "../db/schema";
import { draftReviewerNote } from "./ai";
import { logAction } from "./audit";

const SIM_LABEL =
  "Simulated reviewer — this reply is generated by Tideline and was NOT written or read by a real clinician. It is not medical advice, a diagnosis, or a prescription. For a real review, request a clinician; for anything urgent or life-threatening, call your local emergency number.";

export interface ThreadSummary {
  flag: ReviewFlag;
  lastMessage: ThreadMessage | null;
  unread: number;
}

/**
 * Pure: given a flag and its messages, compute the summary (last message +
 * count of unread reviewer messages). Kept pure so it can be unit-tested and
 * reused without a DB round-trip.
 */
export function summarizeThread(flag: ReviewFlag, messages: ThreadMessage[]): ThreadSummary {
  const ordered = [...messages].sort(
    (a, b) => a.createdAt.getTime() - b.createdAt.getTime(),
  );
  const lastMessage = ordered.length ? ordered[ordered.length - 1] : null;
  const unread = ordered.filter((m) => m.role === "reviewer" && !m.read).length;
  return { flag, lastMessage, unread };
}

/** One summary per review flag: the flag, its latest message, and unread count. */
export async function listThreads(userId: string): Promise<ThreadSummary[]> {
  const flags = await db
    .select()
    .from(reviewFlags)
    .where(eq(reviewFlags.userId, userId))
    .orderBy(desc(reviewFlags.createdAt));
  if (flags.length === 0) return [];

  const messages = await db
    .select()
    .from(threadMessages)
    .where(eq(threadMessages.userId, userId));

  const byFlag = new Map<string, ThreadMessage[]>();
  for (const m of messages) {
    if (!m.reviewFlagId) continue;
    const arr = byFlag.get(m.reviewFlagId) ?? [];
    arr.push(m);
    byFlag.set(m.reviewFlagId, arr);
  }

  return flags.map((flag) => summarizeThread(flag, byFlag.get(flag.id) ?? []));
}

/** Ownership-scoped: the flag + its messages (oldest first), or null. */
export async function getThread(
  userId: string,
  reviewFlagId: string,
): Promise<{ flag: ReviewFlag; messages: ThreadMessage[] } | null> {
  const [flag] = await db
    .select()
    .from(reviewFlags)
    .where(and(eq(reviewFlags.id, reviewFlagId), eq(reviewFlags.userId, userId)));
  if (!flag) return null;

  const messages = await db
    .select()
    .from(threadMessages)
    .where(
      and(eq(threadMessages.userId, userId), eq(threadMessages.reviewFlagId, reviewFlagId)),
    )
    .orderBy(asc(threadMessages.createdAt));

  return { flag, messages };
}

/**
 * Post a message from the user, then generate a SIMULATED reviewer auto-reply.
 * The reply is conservative and clearly labeled simulated. Returns both rows.
 */
export async function postMessage(
  userId: string,
  reviewFlagId: string,
  body: string,
): Promise<{ user: ThreadMessage; reviewer: ThreadMessage } | null> {
  const trimmed = body.trim();
  if (!trimmed) return null;

  // Verify ownership before writing.
  const [flag] = await db
    .select()
    .from(reviewFlags)
    .where(and(eq(reviewFlags.id, reviewFlagId), eq(reviewFlags.userId, userId)));
  if (!flag) return null;

  const [userRow] = await db
    .insert(threadMessages)
    .values({
      userId,
      reviewFlagId,
      role: "user",
      body: trimmed,
      read: true,
      simulated: false,
    })
    .returning();

  const replyBody = await buildSimulatedReply(userId, flag, trimmed);

  const [reviewerRow] = await db
    .insert(threadMessages)
    .values({
      userId,
      reviewFlagId,
      role: "reviewer",
      body: replyBody,
      read: false,
      simulated: true,
    })
    .returning();

  await logAction(userId, "message.post", { reviewFlagId });
  return { user: userRow, reviewer: reviewerRow };
}

/** Compose the simulated reviewer reply text (always prefixed with the label). */
async function buildSimulatedReply(
  userId: string,
  flag: ReviewFlag,
  userBody: string,
): Promise<string> {
  const ctx = flag.context as Record<string, unknown>;
  try {
    const note = await draftReviewerNote({
      source: (flag.source === "insight" ? "insight" : "chat") as "chat" | "insight",
      summary: String(
        ctx.summary ?? ctx.title ?? "A monitoring signal was flagged for review.",
      ),
      severity: ctx.severity ? String(ctx.severity) : undefined,
      details: `${ctx.details ? String(ctx.details) + " " : ""}The person wrote: "${userBody}"`,
    });
    return `**${SIM_LABEL}**\n\n${note}`;
  } catch {
    return safeTemplateReply();
  }
}

/** A conservative fallback reply when the drafter is unavailable. */
function safeTemplateReply(): string {
  return [
    `**${SIM_LABEL}**`,
    "",
    "Thanks for the message. Based on what you've shared, this is most likely something to keep tracking rather than an emergency — short-term shifts are often explained by sleep, stress, illness, hydration, or recent activity.",
    "",
    "Suggested next steps:",
    "- Keep logging how you feel and any new or worsening symptoms.",
    "- If the pattern continues for another 1–2 weeks, see a clinician and bring this timeline.",
    "- Seek care sooner if any new or severe symptoms develop.",
    "",
    "This is general information only, not a diagnosis or prescription.",
  ].join("\n");
}

/** Mark every reviewer message in a thread as read (ownership-scoped). */
export async function markThreadRead(userId: string, reviewFlagId: string): Promise<void> {
  // Verify ownership before writing.
  const [flag] = await db
    .select()
    .from(reviewFlags)
    .where(and(eq(reviewFlags.id, reviewFlagId), eq(reviewFlags.userId, userId)));
  if (!flag) return;

  await db
    .update(threadMessages)
    .set({ read: true })
    .where(
      and(eq(threadMessages.userId, userId), eq(threadMessages.reviewFlagId, reviewFlagId)),
    );
}
