import Link from "next/link";
import { Inbox as InboxIcon, MessageSquare, Info } from "lucide-react";
import { getSessionUser } from "@/lib/auth";
import { listThreads } from "@/lib/services/messages";
import { timeAgo } from "@/lib/utils";

const STATUS_CHIP: Record<string, { cls: string; label: string }> = {
  open: { cls: "watch", label: "Open" },
  in_review: { cls: "info", label: "In review (simulated)" },
  resolved: { cls: "ok", label: "Resolved" },
};

export default async function InboxPage() {
  const user = await getSessionUser();
  const threads = await listThreads(user!.id);

  return (
    <div className="wrap" style={{ marginBottom: 60 }}>
      <div className="page-head">
        <div>
          <h1 className="serif h1">Care-team inbox</h1>
          <p className="sub">Message about your flagged reviews and read the replies.</p>
        </div>
      </div>

      <div className="disclaimer" style={{ marginTop: 4, marginBottom: 20 }}>
        <Info />
        <span>
          Every reply here is <strong>simulated</strong> — generated by Tideline, not written or read
          by a real clinician. It is not a diagnosis or a prescription. For anything urgent or
          life-threatening, call your local emergency number.
        </span>
      </div>

      {threads.length === 0 ? (
        <div className="empty">
          <div className="badge-ic">
            <InboxIcon />
          </div>
          <h2 className="serif h2">No conversations yet</h2>
          <p>
            Flag an insight or request a visit to open a review. You can then message the (simulated)
            care team here and read their replies.
          </p>
          <div className="row">
            <span className="chip">
              <MessageSquare /> Async messaging
            </span>
          </div>
        </div>
      ) : (
        <div className="panel" style={{ marginTop: 8 }}>
          {threads.map(({ flag, lastMessage, unread }) => {
            const ctx = flag.context as Record<string, unknown>;
            const chip = STATUS_CHIP[flag.status] ?? STATUS_CHIP.open;
            const preview = lastMessage
              ? `${lastMessage.role === "reviewer" ? "Simulated reviewer: " : "You: "}${lastMessage.body.replace(/[#*_>`]/g, "").trim()}`
              : "No messages yet — start the conversation.";
            const when = lastMessage ? lastMessage.createdAt : flag.createdAt;
            return (
              <Link className="conn-item" href={`/app/inbox/${flag.id}`} key={flag.id}>
                <span className="ic">
                  <MessageSquare />
                </span>
                <div className="body">
                  <div className="n">
                    {String(ctx.summary ?? ctx.title ?? "Review request")}
                    {unread > 0 && (
                      <span className="chip" style={{ marginLeft: 8 }}>
                        {unread} new
                      </span>
                    )}
                  </div>
                  <div className="s" style={{ whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 520 }}>
                    {preview}
                  </div>
                  <div className="s" style={{ fontSize: 12, color: "var(--muted-2)" }}>
                    Updated {timeAgo(when)}
                  </div>
                </div>
                <span className={`status ${chip.cls}`}>
                  <span className="dot" />
                  {chip.label}
                </span>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}
