import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, User as UserIcon, Stethoscope, Info } from "lucide-react";
import { getSessionUser } from "@/lib/auth";
import { getThread, markThreadRead } from "@/lib/services/messages";
import { Markdown } from "@/components/markdown";
import { MessageComposer } from "@/components/inbox/message-composer";
import { timeAgo } from "@/lib/utils";

const STATUS_CHIP: Record<string, { cls: string; label: string }> = {
  open: { cls: "watch", label: "Open" },
  in_review: { cls: "info", label: "In review (simulated)" },
  resolved: { cls: "ok", label: "Resolved" },
};

export default async function InboxThreadPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const user = await getSessionUser();
  const thread = await getThread(user!.id, id);
  if (!thread) notFound();
  const { flag, messages } = thread;
  const ctx = flag.context as Record<string, unknown>;
  const chip = STATUS_CHIP[flag.status] ?? STATUS_CHIP.open;

  // Mark the (simulated) reviewer messages read now that the thread is open.
  await markThreadRead(user!.id, id);

  return (
    <div className="wrap" style={{ maxWidth: 900, marginBottom: 60 }}>
      <div style={{ paddingTop: 28 }}>
        <Link className="chip soft" href="/app/inbox">
          <ArrowLeft /> Inbox
        </Link>
      </div>

      <div className="page-head" style={{ paddingTop: 18 }}>
        <div>
          <h1 className="serif h2">{String(ctx.summary ?? ctx.title ?? "Review request")}</h1>
          <p className="sub">
            From {flag.source} · opened {timeAgo(flag.createdAt)}
          </p>
        </div>
        <div className="head-actions">
          <span className={`status ${chip.cls}`}>
            <span className="dot" />
            {chip.label}
          </span>
        </div>
      </div>

      <div className="disclaimer" style={{ marginTop: 4, marginBottom: 20 }}>
        <Info />
        <span>
          The care team here is <strong>simulated</strong> — replies are generated by Tideline, not
          written or read by a real clinician, and are not a diagnosis or prescription. For anything
          urgent or life-threatening, call your local emergency number.
        </span>
      </div>

      <div className="box">
        <div className="bhead">Conversation</div>
        {messages.length === 0 ? (
          <div className="ins" style={{ borderBottom: "none" }}>
            <p style={{ marginBottom: 6 }}>
              No messages yet. Send a message below and the (simulated) care team will reply.
            </p>
          </div>
        ) : (
          messages.map((m) => {
            const isReviewer = m.role === "reviewer";
            return (
              <div className="ins" key={m.id}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
                  <span className="ic" style={{ width: 28, height: 28 }}>
                    {isReviewer ? <Stethoscope size={15} /> : <UserIcon size={15} />}
                  </span>
                  <strong>{isReviewer ? "Simulated reviewer" : "You"}</strong>
                  {isReviewer && (
                    <span className="status info">
                      <span className="dot" />
                      Simulated
                    </span>
                  )}
                  <span style={{ marginLeft: "auto", fontSize: 12, color: "var(--muted-2)" }}>
                    {timeAgo(m.createdAt)}
                  </span>
                </div>
                <Markdown content={m.body} />
              </div>
            );
          })
        )}
      </div>

      <div className="box" style={{ marginTop: 20 }}>
        <div className="bhead">Send a message</div>
        <MessageComposer reviewFlagId={flag.id} />
      </div>
    </div>
  );
}
